### ISSUE TITLE
Remove temporary MapOf after new Atoms release

### ISSUE THREAD

**Issue by icaOBU** [icarus-consulting/Yaapii.Http#86]
### Expected Behavior

The QueryParams object uses the MapOf from Yaapii.Atoms. Remove the temporary class after new release from Yaapii.Atoms (>2.3.1)
### Actual Behavior

Temporary MapOf is used due to missing Atoms release

**Comment by DFU398** [comment]
Is this already fixed? As far as i can see, there are no temporary Atoms classes in Yaapii.Http anymore and we are using Yaapii.Atoms 3.0.0

**Comment by DFU398** [comment]
solved in #120
